### ISSUE TITLE
Publish null-safe version?

### ISSUE THREAD

**Issue by TimWhiting** [dart-lang/crypto#105]
Hi, it looks like this package is already migrated, but doesn't have a null-safe version published to pub.dev.
Now that null-safety is in beta, maybe this could be done? This is blocking other packages such as `dartx` from migrating.

Thanks!

**Comment by MisterJimson** [comment]
Agreed. Is there a blocker for publishing we could help with?

**Comment by shinayser** [comment]
@natebosch There is anything blocking this issue for being closed?

**Comment by natebosch** [comment]
This is published.
