### ISSUE TITLE
Linking to the test/continuous integration server results?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/crypto#11]
It's common to link to where the latest CI system's output is. For example, if this were using Travis, we could link to the latest Travis results.

This package might be tested on the package bots? If so, can we link to there?

Thanks!

**Comment by sethladd** [comment]
cc @whesse who might know

**Comment by sethladd** [comment]
or @sgjesse who might know if this is tested and if so, where the bots are.

**Comment by whesse** [comment]
This package is tested on the package waterfall, at http://build.chromium.org/p/client.dart.packages/console

The individual builders are at:
https://uberchromegw.corp.google.com/i/client.dart.packages/builders/packages-mac-crypto
https://uberchromegw.corp.google.com/i/client.dart.packages/builders/packages-linux-crypto
https://uberchromegw.corp.google.com/i/client.dart.packages/builders/packages-windows-crypto

**Comment by whesse** [comment]
This package is tested on the package waterfall, at http://build.chromium.org/p/client.dart.packages/console

The individual builders are at:
http://build.chromium.org/p/client.dart.packages/builders/packages-windows-crypto
http://build.chromium.org/p/client.dart.packages/builders/packages-linux-crypto
http://build.chromium.org/p/client.dart.packages/builders/packages-mac-crypto

**Comment by sethladd** [comment]
Thanks @whesse !
