### ISSUE TITLE
Flutter project fail to build on iphone , the error message is "ld: library not found for -lcrypto" 

### ISSUE THREAD

**Issue by owenchenwifigarden** [dart-lang/crypto#123]
I just upgrade my flutter project to flutter2.0 yesterday, and I can still built it well on android system, but when I want to build on iphone11(os ver:14.8), it will fail.

Xcode version is 13.1, the error message and flutter doctor screenshot is as below.
<img width="268" alt="139392161-a8b69702-711c-443e-ac17-71307ea1ac91" src="https://user-images.githubusercontent.com/74166223/140016617-fb6e4ecd-42c4-42db-995f-71b2e204fe0c.png">
<img width="986" alt="139392173-d05bb6db-d0f1-4b05-a5aa-f653cb4408db" src="https://user-images.githubusercontent.com/74166223/140016621-fb8655eb-b236-44ef-bce9-f8664a77b117.png">

And Attached file are the 

1. flutter run -verbose log
2. pubspec.yaml
3. podfile

Thanks a lot.

Btw, I have asked at flutter repo couple days ago, hyperlink as follow.
https://github.com/flutter/flutter/issues/92706

**Comment by natebosch** [comment]
The user who pointed you here had a misunderstanding. The error is unrelated to Dart code.

https://github.com/flutter/flutter/issues/92706#issuecomment-960342876

**Comment by owenchenwifigarden** [comment]
@natebosch Oh! Thanks and sorry for bothering you, I'll try to find this out.
