### ISSUE TITLE
Redefinition of module 'CommonCrypto' module CommonCrypto

### ISSUE THREAD

**Issue by hiteshsapra** [dart-lang/crypto#124]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/CommonCrypto/module.modulemap:1:8: error: redefinition of module 'CommonCrypto'
module CommonCrypto [system] [extern_c] {
       ^
/Users/hits/WorkPlace/project/zapit-wallet/ios/Pods/SCrypto/Frameworks/iphonesimulator/CommonCrypto.framework/module.map:1:8: note: previously defined here
module CommonCrypto [system] {
       ^
Command MergeSwiftModule failed with a nonzero exit code

**Comment by devoncarew** [comment]
Thanks for the issue; I don't think what you're seeing above is related to package:crypto however.
