### ISSUE TITLE
sha256 encryption file data obtained by dart is inconsistent with that obtained by openssl dgst-sha256

### ISSUE THREAD

**Issue by wsb1689** [dart-lang/crypto#133]
this is my file :
![171666951407_ pic](https://user-images.githubusercontent.com/16127597/198567174-d7a147b2-b9cb-4154-b974-031a6b985177.jpg)

this is my code

```
void selectLocalFile() async {
    try {
      FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: [
          'jpg',
          'pdf',
          'doc',
          'png',
          'mov',
          'mp4',
          'ppt',
          'xls'
        ],
      );
      if (result != null) {
        File file = File(result.files.single.path!);
        final value = (await sha256.bind(file.openRead()).first).toString();
       // value: 5ff9277089d9ed80317fdf385c5ed40f6fa101c8a18262e3e143ff07bef0bc7e
      // openssl dgst-sha256 <filepath>  cf8fe051aebdf202509a92110017a35a698034b18e36cbf4b4df138b00081a25
        _localPath.value = value;
        wjLogString(msg: "加密的数据：${_localPath.value}");
      } else {
        wjLogString(msg: "无法获取选择的文件");
      }
    } catch (e) {
      wjLogString(msg: "FilePickerResult:error---$e");
    } // User canceled the picker
  }
```

flutter doctor -v:
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.0.0 at /Users/gc/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gc/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/gc/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119
    ! Error: 荀芹云的 iPhone is not connected. Xcode will continue when 荀芹云的 iPhone
      is connected. (code -13)
    ! Error: bjt💙 is not connected. Xcode will continue when bjt💙 is
      connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by devoncarew** [comment]
Thanks again for the report! When I run your sample file through the example/ cli tool (https://github.com/dart-lang/crypto/blob/master/example/example.dart), I see

> dart example/example.dart sha256 bug_133.jpg
> cf8fe051aebdf202509a92110017a35a698034b18e36cbf4b4df138b00081a25

Which is what you show for openssl dgst-sha256, so I suspect some issue with the above code or methodology.

**Comment by wsb1689** [comment]
@devoncarew Hello, can you paste your code? I'd like to refer to it，very thanks

**Comment by devoncarew** [comment]
It's that link in my comment above - a link to the example/example.dart file in this repo.
