### ISSUE TITLE
Dart 3 incompatibilty: `DigestSink extends Sink` but `Sink` is `interface class`

### ISSUE THREAD

**Issue by oprypin** [dart-lang/crypto#145]
```
The class 'Sink' can't be extended outside of its library because it's an interface class.
class DigestSink extends Sink<Digest> {
                         ^
```

https://github.com/dart-lang/crypto/blob/1cb1528bbc361206dcc2f50df30b08db4cb99cf4/lib/src/digest_sink.dart#L8

cc @lrhn @natebosch

Base definition: https://github.com/dart-lang/sdk/blame/fb43937e201b76a3a53cb5bb6a001b4c79463939/sdk/lib/core/sink.dart#L13

**Comment by lrhn** [comment]
Should only be a problem when the class is updated to language version 3.0.
Before that the `extends` should be changed to `implements`: https://github.com/dart-lang/crypto/pull/146
