### ISSUE TITLE
Flutter 3.13.4 Latest version :  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'KeyParameter' is not a subtype of type 'PaddedBlockCipherParameters<CipherParameters?, CipherParameters?>' of 'params' 

### ISSUE THREAD

**Issue by parmarravi** [dart-lang/crypto#152]
I have updated the Flutter version for the project

![unnamed (2)](https://github.com/dart-lang/crypto/assets/7616089/d3500375-a354-436b-bc4c-e48768805e63)

But now i am getting  this Error

![unnamed (1)](https://github.com/dart-lang/crypto/assets/7616089/3ea68005-4bed-411b-899c-5b2a7d460f1a)

Code

![image (2)](https://github.com/dart-lang/crypto/assets/7616089/2de1ec55-4538-4252-b3fd-ef7201cf66ec)

**Comment by devoncarew** [comment]
I believe this is an issue for the the `encrypt` package, not this package. You might file an issue on their repo (and / or try upgrading to the latest version of that package).
