### ISSUE TITLE
Base64 shouldn't choke on high-codepoint strings

### ISSUE THREAD

**Issue by nex3** [dart-lang/crypto#17]
Currently, the Base64 decoder crashes when passed a string containing a character with a codepoint above 256. It shouldn't accept this, but it should throw a more useful error.

**Comment by sethladd** [comment]
I believe all the base64 stuff is getting moved.

cc @sgjesse @whesse

**Comment by nex3** [comment]
I think that's right; we can move the issues along with it once it does, if I don't get around to fixing them first.

**Comment by kevmoo** [comment]
Base64 APIs were removed in https://github.com/dart-lang/crypto/commit/72c74719a78cc5f4e162023ca5b17d3a53d3cd4c
