### ISSUE TITLE
Base64 should reject interstitial padding characters

### ISSUE THREAD

**Issue by nex3** [dart-lang/crypto#19]
Currently, if there are a multiple of four `=` or `%3D` sequences in a Base64 string, the parser will treat them as zero bytes. This is clearly wrong; it should reject those strings like it does for strings with other numbers of `=`.

**Comment by kevmoo** [comment]
Base64 APIs were removed in https://github.com/dart-lang/crypto/commit/72c74719a78cc5f4e162023ca5b17d3a53d3cd4c
