### ISSUE TITLE
expose `DigestSink` for chunked conversions

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/crypto#42]
There is a `startChunkedConversion` api on the `Hash` class [here](https://github.com/dart-lang/crypto/blob/master/lib/src/hash.dart#L34), but you can't use it easily without an import to `lib/src/` because the `DigestSink` class is not exposed (as far as I can tell at least).

**Comment by nex3** [comment]
Can you use [`AccumulatorSink`](https://www.dartdocs.org/documentation/convert/2.0.1/convert/AccumulatorSink-class.html) from the `convert` for your use-case? It's more general-purpose, and if it works I'd like to avoid exposing a very narrow internal class if possible.

**Comment by jakemac53** [comment]
That worked fine for my case, thanks!

It might be worth adding something to the readme about how to do chunked conversions.

**Comment by nex3** [comment]
I think the place for that is really the core `Converter` class—it's pretty confusing how to use chunked conversion for any converter, not just `Hash`.

**Comment by greglittlefield-wf** [comment]
Should the example linked below be updated to use AccumulatorSink instead of recommending src/ imports?

https://github.com/dart-lang/crypto#digest-on-chunked-input

**Comment by kevmoo** [comment]
@greglittlefield-wf – PR welcome!

**Comment by greglittlefield-wf** [comment]
@kevmoo PR up! https://github.com/dart-lang/crypto/pull/61
