### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by ManojMM026** [dart-lang/crypto#74]
```
ecause every version of flutter_driver from sdk depends on crypto 2.0.6 and example depends on crypto ^2.1.2, flutter_driver from sdk is forbidden.
So, because example depends on flutter_driver any from sdk, version solving failed.

pub get failed (1)
```

**Comment by gbIxaHue** [comment]
+1
Because every version of flutter_test from sdk depends on crypto 2.1.3 and love_game depends on crypto ^2.1.4, flutter_test from sdk is forbidden.

**Comment by natebosch** [comment]
The flutter SDK pins package versions. Please ask them to upgrade versions when you are stuck version solving because of a dependency from their packages. This isn't something we can solve here.
