### ISSUE TITLE
The size of the output of HMAC is no the same as that of the underlying hash function

### ISSUE THREAD

**Issue by marcelgarus** [dart-lang/crypto#82]
The size of the output of HMAC should be the same as that of the underlying hash function. However, that's not the case. For example, the following code fails:

```dart
final hash = sha256;
final converted = Hmac(hash, utf8.encode('some key'))
    .convert(utf8.encode('some data'))
    .bytes;
assert(hash.blockSize == converted.length);
```

**Comment by Synchro** [comment]
This isn't correct - The block size is not necessarily the same as the output length - for SHA256, the block size is 512. [See this table](https://en.wikipedia.org/wiki/Comparison_of_cryptographic_hash_functions#Parameters).

**Comment by marcelgarus** [comment]
Oh, you're right 😅 sorry, my mistake
